export const CREATE_TOKEN_BOOKING_REQUEST = 'CREATE_TOKEN_BOOKING_REQUEST';
export const CREATE_TOKEN_BOOKING_SUCCESS = 'CREATE_TOKEN_BOOKING_SUCCESS';
export const CREATE_TOKEN_BOOKING_FAIL = 'CREATE_TOKEN_BOOKING_FAIL';

export const GET_USER_TOKEN_BOOKINGS_REQUEST = 'GET_USER_TOKEN_BOOKINGS_REQUEST';
export const GET_USER_TOKEN_BOOKINGS_SUCCESS = 'GET_USER_TOKEN_BOOKINGS_SUCCESS';
export const GET_USER_TOKEN_BOOKINGS_FAIL = 'GET_USER_TOKEN_BOOKINGS_FAIL';

export const GET_TOKEN_BOOKING_REQUEST = 'GET_TOKEN_BOOKING_REQUEST';
export const GET_TOKEN_BOOKING_SUCCESS = 'GET_TOKEN_BOOKING_SUCCESS';
export const GET_TOKEN_BOOKING_FAIL = 'GET_TOKEN_BOOKING_FAIL';

// Additional aliases used across the codebase
export const GET_TOKEN_BOOKINGS_REQUEST = GET_USER_TOKEN_BOOKINGS_REQUEST;
export const GET_TOKEN_BOOKINGS_SUCCESS = GET_USER_TOKEN_BOOKINGS_SUCCESS;
export const GET_TOKEN_BOOKINGS_FAIL = GET_USER_TOKEN_BOOKINGS_FAIL;

export const GET_TOKEN_BOOKING_DETAILS_REQUEST = GET_TOKEN_BOOKING_REQUEST;
export const GET_TOKEN_BOOKING_DETAILS_SUCCESS = GET_TOKEN_BOOKING_SUCCESS;
export const GET_TOKEN_BOOKING_DETAILS_FAIL = GET_TOKEN_BOOKING_FAIL;

export const UPDATE_TOKEN_BOOKING_STATUS_REQUEST = 'UPDATE_TOKEN_BOOKING_STATUS_REQUEST';
export const UPDATE_TOKEN_BOOKING_STATUS_SUCCESS = 'UPDATE_TOKEN_BOOKING_STATUS_SUCCESS';
export const UPDATE_TOKEN_BOOKING_STATUS_FAIL = 'UPDATE_TOKEN_BOOKING_STATUS_FAIL';

export const CANCEL_TOKEN_BOOKING_REQUEST = 'CANCEL_TOKEN_BOOKING_REQUEST';
export const CANCEL_TOKEN_BOOKING_SUCCESS = 'CANCEL_TOKEN_BOOKING_SUCCESS';
export const CANCEL_TOKEN_BOOKING_FAIL = 'CANCEL_TOKEN_BOOKING_FAIL';

export const UPLOAD_PAYMENT_PROOF_REQUEST = 'UPLOAD_PAYMENT_PROOF_REQUEST';
export const UPLOAD_PAYMENT_PROOF_SUCCESS = 'UPLOAD_PAYMENT_PROOF_SUCCESS';
export const UPLOAD_PAYMENT_PROOF_FAIL = 'UPLOAD_PAYMENT_PROOF_FAIL'; 

// Generic clear errors action
export const CLEAR_ERRORS = 'CLEAR_ERRORS';